name: Build APK
on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Install and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 22.x
      - name: Expo and EAS setup
        uses: expo/expo-github-action@v7
        with:
          expo-version: 6.x
          eas-version: 7.14.0
          token: ${{ secrets.EAS_BUILD }}
      - name: Install dependencies
        run: yarn install
      - name: Build on EAS for preview
        run: eas build -p android --profile preview
